---
    name: CI

    "on":
      pull_request:

    jobs:
      pytest:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.12

          - name: Install dependencies
            run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                uv sync
                wget -O draft7.json http://json-schema.org/draft-07/schema
          - name: Run tests
            run: |
              for f in schemas/*json; do echo Validating ${f}; uv run check-jsonschema --schemafile draft7.json  $f ;done
